services:
  - type: web
    name: fleetwatch-backend
    env: node
    region: oregon
    plan: free
    rootDir: fleetwatch
    buildCommand: npm install && npm run build:server
    startCommand: node dist/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
